Repository boostcampwm-2021/web12-sooltreaming, pull requests merged in 2021-11, with the labels that each got.

#18 [Feature/#1] 에러 토스트 메세지 다같이 완료
  client/package.json
  client/src/App.tsx
  client/src/components/custom/ErrorToast.tsx
  client/src/index.tsx
  client/src/store/error.ts
  client/src/store/user.ts
  server/api/index.ts
  server/api/v1/test.ts
Labels: 기능

#20 [Feature/#19] PR template / auto-assign 플러그인 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
Labels: 설정

#21 [Develop] PR TEST
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  client/package.json
  client/src/App.tsx
  client/src/components/custom/ErrorToast.tsx
  client/src/index.tsx
  client/src/store/error.ts
  client/src/store/user.ts
  server/api/index.ts
  server/api/v1/test.ts
Labels: 설정

#22 [Feature/#9] 소켓 연결하기
  client/package.json
  client/src/App.tsx
  client/src/components/chat-room/Chat.tsx
  client/src/socket/socket.ts
  server/app.ts
  server/loader/basic.ts
  server/loader/index.ts
  server/loader/socket.ts
  server/package.json
  server/utils/pipe.ts
Labels: 기능, 프론트엔드, 백엔드

#24 [Feature/#3] Lobby 컴포넌트 스타일링 및 구조 확립
  client/public/images/human.svg
  client/public/index.html
  client/src/App.tsx
  client/src/Constant.js
  client/src/GlobalStyle.js
  client/src/components/Header.style.js
  client/src/components/Header.tsx
  client/src/pages/Lobby.style.js
  client/src/pages/Lobby.tsx
Labels: 기능, 프론트엔드

#25 [Feature/#15] 채팅 컴포넌트 구현
  client/public/images/paper-plane.svg
  client/src/App.tsx
  client/src/components/chat-room/Chat.style.js
  client/src/components/chat-room/Chat.tsx
  client/src/components/chat-room/ChatForm.style.js
  client/src/components/chat-room/ChatForm.tsx
  client/src/components/custom/ErrorToast.tsx
  client/src/pages/Lobby.tsx
  client/src/socket/message.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  client/src/store/message.ts
  server/controller/socket/chatting.ts
  server/controller/socket/entering.ts
  server/loader/socket.ts
  server/utils/time.ts
Labels: 기능, 프론트엔드, 백엔드

#32 [Feature/#11] URL을 통한 화상채팅방 입장
  client/src/pages/ChatRoom.tsx
  client/src/pages/Lobby.tsx
  client/src/socket/chatRoom.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  server/controller/socket/chatting.ts
  server/controller/socket/creating.ts
  server/controller/socket/entering.ts
  server/controller/socket/signaling.ts
  server/controller/socket/socket.type.ts
  server/loader/socket.ts
Labels: 기능, 리팩토링, 프론트엔드, 백엔드, 설정

#31 [Feature/#27] styled 리팩토링, 화상채팅 방 구조 결정, 메뉴 창 라우팅
  client/src/Constant.js
  client/src/components/Header.style.js
  client/src/components/Header.tsx
  client/src/components/chat-room/Chat.style.js
  client/src/components/chat-room/Chat.tsx
  client/src/components/chat-room/ChatForm.style.js
  client/src/components/chat-room/ChatForm.tsx
  client/src/components/chat-room/ChatItem.style.ts
  client/src/components/chat-room/ChatItem.tsx
  client/src/components/chat-room/ChatMenu.style.js
  client/src/components/chat-room/ChatMenu.tsx
  client/src/pages/ChatRoom.style.js
  client/src/pages/ChatRoom.tsx
  client/src/pages/Lobby.style.js
  client/src/pages/Lobby.tsx
Labels: 기능, 리팩토링, 프론트엔드

#34 [Feature/#16] 영상 및 음성 1대1 공유 구현
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/socket/webRTC.ts
Labels: 기능, 백엔드

#35 [Feature/#11] URL 접근 버그 수정, 리팩토링
  client/src/App.tsx
  client/src/components/chat-room/Chat.tsx
  client/src/pages/ChatRoom.tsx
  client/src/pages/CreateRoom.style.js
  client/src/pages/CreateRoom.tsx
  client/src/pages/Lobby.tsx
  client/src/socket/host.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  server/controller/socket/chatting.ts
  server/controller/socket/creating.ts
  server/controller/socket/entering.ts
Labels: 리팩토링

#36 [Feature/#16] webRTC 다중 유저 연결 & 코드 리팩토링
  client/package.json
  client/src/components/chat-room/Chat.tsx
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/pages/ChatRoom.tsx
  client/src/pages/CreateRoom.tsx
  client/src/socket/host.ts
  client/src/socket/message.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  client/src/socket/webRTC.ts
  client/src/utils/customRTC.ts
  client/tsconfig.json
  server/controller/socket/chatting.ts
  server/controller/socket/creating.ts
  server/controller/socket/entering.ts
  server/controller/socket/signaling.ts
  server/loader/socket.ts
Labels: 기능, 리팩토링, 도와줘요, 프론트엔드, 백엔드

#37 [Develop] 대기실, WebRTC, 채팅 배포
  client/package.json
  client/public/images/human.svg
  client/public/images/paper-plane.svg
  client/public/index.html
  client/src/App.tsx
  client/src/Constant.js
  client/src/GlobalStyle.js
  client/src/components/Header.style.js
  client/src/components/Header.tsx
  client/src/components/chat-room/Chat.style.js
  client/src/components/chat-room/Chat.tsx
  client/src/components/chat-room/ChatForm.style.js
  client/src/components/chat-room/ChatForm.tsx
  client/src/components/chat-room/ChatItem.style.ts
  client/src/components/chat-room/ChatItem.tsx
  client/src/components/chat-room/ChatMenu.style.js
  client/src/components/chat-room/ChatMenu.tsx
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/components/chat-room/chat-room.ts
  client/src/components/custom/ErrorToast.tsx
  client/src/pages/ChatRoom.style.js
  client/src/pages/ChatRoom.ts
  client/src/pages/ChatRoom.tsx
  client/src/pages/CreateRoom.style.js
  client/src/pages/CreateRoom.tsx
  client/src/pages/Lobby.style.js
  client/src/pages/Lobby.ts
  client/src/pages/Lobby.tsx
  client/src/socket/host.ts
  client/src/socket/message.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  client/src/socket/webRTC.ts
  client/src/store/message.ts
  client/src/utils/customRTC.ts
  client/tsconfig.json
  server/app.ts
  server/controller/socket/chatRoomController.ts
  server/controller/socket/chatting.ts
  server/controller/socket/creating.ts
  server/controller/socket/entering.ts
  server/controller/socket/signaling.ts
  server/controller/socket/socket.type.ts
  server/loader/basic.ts
  server/loader/index.ts
  server/loader/mongo.ts
  server/loader/socket.ts
  server/package.json
  server/utils/pipe.ts
  server/utils/time.ts
Labels: 배포

#30 [Documentation] README.md issue, PR 수 추가
  .github/workflows/release.yml
  README.md
Labels: 문서

#55 [Develop] Github Action 리뷰 받기, README 수정
  .github/workflows/release.yml
  README.md
Labels: 문서, 설정

#57 [Feature/#56] 리뷰 투게더 코드 반영 및 코드 컨벤션 확립
  client/package.json
  client/public/images/human.svg
  client/public/images/paper-plane.svg
  client/src/api/api.ts
  client/src/components/Header.style.js
  client/src/components/Header.tsx
  client/src/components/chat-room/Chat.style.js
  client/src/components/chat-room/Chat.tsx
  client/src/components/chat-room/ChatForm.style.js
  client/src/components/chat-room/ChatForm.tsx
  client/src/components/chat-room/ChatItem.style.ts
  client/src/components/chat-room/ChatItem.tsx
  client/src/components/chat-room/ChatMenu.style.js
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/components/icons/HumanIcon.tsx
  client/src/components/icons/PaperPlaneIcon.tsx
  client/src/components/icons/index.ts
  client/src/constant/style.js
  client/src/pages/ChatRoom.style.js
  client/src/pages/ChatRoom.tsx
  client/src/pages/CreateRoom.style.js
  client/src/pages/Lobby.style.js
  client/src/socket/user.ts
  client/src/socket/webRTC.ts
  client/tsconfig.alias.json
  client/tsconfig.json
  server/controller/socket/chatRoomController.ts
  server/controller/socket/socket.type.ts
  server/package.json
  server/src/api/index.ts
  server/src/api/v1/auth.ts
  server/src/api/v1/friend.ts
  server/src/api/v1/index.ts
  server/src/api/v1/rank.ts
  server/src/api/v1/test.ts
  server/src/api/v1/user.ts
  server/src/app.ts
  server/src/controller/login.ts
  server/src/controller/socket/chatting.ts
  server/src/controller/socket/creating.ts
  server/src/controller/socket/entering.ts
  server/src/controller/socket/signaling.ts
  server/src/loader/basic.ts
  server/src/loader/index.ts
  server/src/loader/mongo.ts
  server/src/loader/socket.ts
  server/src/models/LiarGameKeywords.ts
  server/src/models/NicknameLog.ts
  server/src/models/User.ts
  server/src/models/index.ts
  server/src/utils/pipe.ts
  server/src/utils/time.ts
  server/tsconfig.json
Labels: 리팩토링

#59 [Feature/#58] 클라이언트 기기 설정 병합 / URL 설정
  .github/workflows/release.yml
  client/package.json
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/components/chat-room/ChatRoom.style.js
  client/src/components/chat-room/ChatRoom.tsx
  client/src/components/custom/Dropdown.style.js
  client/src/components/custom/Dropdown.tsx
  client/src/components/icons/DownIcon.tsx
  client/src/components/icons/HumanIcon.tsx
  client/src/components/icons/MicIcon.tsx
  client/src/components/icons/PaperPlaneIcon.tsx
  client/src/components/icons/VideoIcon.tsx
  client/src/components/icons/XIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/setting/SettingMenu.style.ts
  client/src/components/setting/SettingMenu.tsx
  client/src/components/setting/SettingWindow.style.js
  client/src/components/setting/SettingWindow.tsx
  client/src/constant/style.js
  client/src/pages/Setting.style.js
  client/src/pages/Setting.tsx
  client/src/socket/socket.ts
  client/src/socket/webRTC.ts
  client/src/store/device.ts
  server/package.json
  server/src/loader/socket.ts
Labels: 기능, 리팩토링, 배포, 프론트엔드, 백엔드

#61 [Hotfix] Stream 미생성으로 인한 커넥션 오류 해결
  client/src/components/chat-room/ChatRoom.tsx
  client/src/components/custom/Loading.style.js
  client/src/components/custom/Loading.tsx
  client/src/components/setting/SettingWindow.style.js
  client/src/components/setting/SettingWindow.tsx
  client/src/pages/CreateRoom.tsx
  client/src/socket/webRTC.ts
Labels: 오류

#65 [Feature/#47] Github, Naver 로그인 구현 및 클라이언트 로그인 가능
  client/public/favicon.ico
  client/public/images/github-login.png
  client/public/images/github-logo.png
  client/public/images/naver-login.png
  client/public/images/naver-logo.png
  client/src/App.tsx
  client/src/api/api.ts
  client/src/api/user.ts
  client/src/components/Header.tsx
  client/src/components/custom/ServerError.style.js
  client/src/components/custom/ServerError.tsx
  client/src/constant/envs.js
  client/src/pages/Lobby.tsx
  client/src/pages/Login.style.js
  client/src/pages/Login.ts
  client/src/pages/Login.tsx
  client/src/pages/Splash.tsx
  client/src/socket/socket.ts
  client/src/store/user.ts
  client/src/utils/request.ts
  server/package.json
  server/src/api/v1/auth.ts
  server/src/api/v1/index.ts
  server/src/app.ts
  server/src/constant.ts
  server/src/controller/login.ts
  server/src/controller/passport/github.ts
  server/src/controller/passport/naver.ts
  server/src/loader/basic.ts
  server/src/loader/index.ts
  server/src/loader/mongo.ts
  server/src/loader/passport.ts
  server/src/loader/socket.ts
  server/src/models/User.ts
Labels: 기능, 프론트엔드, 백엔드, 설정

#75 [Feature/#74] 3주차 내용 리팩토링 및 버그 수정
  client/src/components/animation/AnimationScreen.tsx
  client/src/components/animation/QuestionMark.tsx
  client/src/components/chat-room/ChatForm.tsx
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/components/chat-room/ChatRoom.tsx
  client/src/components/chat-room/ControlBar.tsx
  client/src/components/chat-room/Menu.tsx
  client/src/components/icons/SpeakerIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/setting/PrevSetting.tsx
  client/src/components/setting/RoomSetting.tsx
  client/src/components/setting/SettingMenu.style.js
  client/src/constant/envs.js
  client/src/hooks/useSetting.tsx
  client/src/hooks/useToggleSpeaker.ts
  client/src/hooks/useUpdateSpeaker.ts
  client/src/hooks/useUpdateStream.ts
  client/src/index.tsx
  client/src/pages/Lobby.tsx
  client/src/pages/Setting.tsx
  client/src/sagas/device.ts
  client/src/socket/webRTC.ts
  client/src/store/device.ts
  client/src/utils/customRTC.ts
  server/src/controller/socket/animation.ts
  server/src/controller/socket/chatting.ts
  server/src/controller/socket/entering.ts
  server/src/controller/socket/questionMark.ts
Labels: 기능, 리팩토링, 도와줘요, 스타일, 프론트엔드, 백엔드, 설정

#107 [Feature/#86] 자발적 클로즈업
  client/src/components/chat-room/ChatMonitor.style.ts
  client/src/components/chat-room/ChatMonitor.tsx
  client/src/components/chat-room/ChatRoom.style.js
  client/src/components/chat-room/ChatRoom.tsx
  client/src/components/chat-room/ControlBar.tsx
  client/src/components/chat-room/Menu.tsx
  client/src/components/user/Users.style.js
  client/src/components/user/Users.tsx
  client/src/components/user/user.ts
  client/src/socket/animation.ts
  client/src/socket/user.ts
  server/src/controller/socket/animation.ts
  server/src/controller/socket/creating.ts
  server/src/controller/socket/entering.ts
  server/src/loader/socket.ts
Labels: 기능, 프론트엔드, 백엔드

#108 [Feature/#82] 커스텀 모달 작성 및 투표 스타일링
  client/public/images/agree.png
  client/public/images/bomb.png
  client/public/images/disagree.png
  client/src/components/chat-room/ChatRoom.tsx
  client/src/components/chat-room/scaffold/TimerBomb.style.js
  client/src/components/chat-room/scaffold/TimerBomb.tsx
  client/src/components/chat-room/scaffold/index.style.js
  client/src/components/chat-room/scaffold/index.tsx
  client/src/components/custom/Modal.style.ts
  client/src/components/custom/Modal.tsx
  client/src/pages/Login.tsx
Labels: 기능, 프론트엔드

#109 [Feature/#99] 방장 권한 관련 기능 작업
  client/src/components/animation/AnimationScreen.tsx
  client/src/components/chat-room/Chat.tsx
  client/src/components/chat-room/ChatRoom.tsx
  client/src/components/chat-room/Menu.tsx
  client/src/components/chat-room/host/Host.style.js
  client/src/components/chat-room/host/Host.tsx
  client/src/components/chat-room/host/ParticipantController.tsx
  client/src/components/chat-room/host/RoomController.style.ts
  client/src/components/chat-room/host/RoomController.tsx
  client/src/components/icons/CopyIcon.tsx
  client/src/components/icons/index.ts
  client/src/constant/envs.js
  client/src/socket/roomControl.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  client/src/store/index.ts
  client/src/store/room.ts
  server/src/controller/socket/entering.ts
  server/src/controller/socket/restricting.ts
  server/src/loader/socket.ts
Labels: 기능, 프론트엔드, 백엔드

#112 [Hotfix] 필요없는 파일 제거 및 절대경로 수정
  client/src/components/lobby/lobby.ts
  client/src/components/room/animation-screen/index.tsx
  client/src/components/room/host/RoomController.tsx
  client/src/components/room/host/index.tsx
  client/src/components/room/monitor/index.tsx
  client/src/hooks/hook.ts
  client/src/pages/Lobby.tsx
  client/src/pages/Login.tsx
  client/src/socket/socket.ts
  client/src/utils/utils.ts
Labels: 리팩토링

#113 [Feature/#78] 단두대 기능 작동 및 UI 구성
  client/public/images/agree.png
  client/public/images/bomb.png
  client/public/images/disagree.png
  client/src/components/icons/VoterIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/room/scaffold/TimerBomb.style.js
  client/src/components/room/scaffold/VotePresser.style.js
  client/src/components/room/scaffold/VotePresser.tsx
  client/src/components/room/scaffold/Voters.style.js
  client/src/components/room/scaffold/Voters.tsx
  client/src/components/room/scaffold/index.style.ts
  client/src/components/room/scaffold/index.tsx
  client/src/hooks/socket/useVote.ts
  client/src/socket/socket.ts
  client/src/socket/vote.ts
  client/src/store/room.ts
  server/src/controller/socket/creating.ts
  server/src/controller/socket/entering.ts
  server/src/controller/socket/restricting.ts
  server/src/controller/socket/videoChange.ts
  server/src/controller/socket/voting.ts
  server/src/loader/socket.ts
Labels: 기능, 리팩토링, 프론트엔드, 백엔드

#115 [Feature/#80] 참가자 닉네임 송출 및 친구 신청
  client/src/api/user.ts
  client/src/components/room/index.tsx
  client/src/components/room/monitor/index.style.ts
  client/src/components/room/monitor/index.tsx
  client/src/components/user/Users.tsx
  client/src/constant/style.js
  client/src/sagas/friend.ts
  client/src/sagas/index.ts
  client/src/store/friend.ts
  client/src/store/index.ts
  server/src/api/v1/friend.ts
  server/src/api/v1/index.ts
Labels: 기능, 스타일, 프론트엔드, 백엔드

#114 [Feature/#79] 사용자 정보페이지 일부 구현
  client/public/images/ImgBox.png
  client/public/images/LeftIcon.png
  client/public/images/check.png
  client/public/images/deny.png
  client/public/images/requestFriend.png
  client/public/images/xbutton.png
  client/src/App.tsx
  client/src/api/user.ts
  client/src/components/Header.tsx
  client/src/components/custom/Modal.tsx
  client/src/components/icons/ChangeNicknameIcon.tsx
  client/src/components/icons/DeleteFriendIcon.tsx
  client/src/components/icons/ExitIcon.tsx
  client/src/components/icons/FriendHomeIcon.tsx
  client/src/components/icons/HistoryIcon.tsx
  client/src/components/icons/LeftIcon.tsx
  client/src/components/icons/SmallAcceptIcon.tsx
  client/src/components/icons/SmallCancelIcon.tsx
  client/src/components/icons/SmallRejectIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/room/ControlBar.tsx
  client/src/components/user-information/FriendList.style.js
  client/src/components/user-information/FriendList.tsx
  client/src/components/user-information/Information.style.js
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/MainData.tsx
  client/src/components/user-information/Ranking.style.js
  client/src/components/user-information/Ranking.tsx
  client/src/components/user-information/user-information.ts
  client/src/components/user/Users.tsx
  client/src/pages/UserInformation.style.js
  client/src/pages/UserInformation.ts
  client/src/pages/UserInformation.tsx
  client/src/store/user.ts
  client/src/utils/request.ts
  server/package.json
  server/src/api/v1/index.ts
  server/src/api/v1/user.ts
  server/src/controller/socket/animation.ts
  server/src/controller/socket/chatting.ts
  server/src/controller/socket/logController.ts
  server/src/controller/socket/questionMark.ts
  server/src/controller/user/user.ts
  server/src/utils/error.ts
Labels: 기능, 리팩토링, 도와줘요, 프론트엔드, 백엔드

#117 [Feature/#78] 단두대 기능 다른 사람과 함께 진행할 수 있어용~
  client/src/components/room/ControlBar.tsx
  client/src/components/room/RoomMenu.tsx
  client/src/components/room/host/ParticipantController.tsx
  client/src/components/room/index.tsx
  client/src/components/room/scaffold/index.tsx
  client/src/components/user/Users.tsx
  client/src/hooks/socket/useUser.ts
  client/src/hooks/socket/useVote.ts
  client/src/store/room.ts
  server/src/controller/socket/animation.ts
  server/src/controller/socket/creating.ts
  server/src/controller/socket/entering.ts
  server/src/controller/socket/restricting.ts
  server/src/controller/socket/voting.ts
  server/src/loader/socket.ts
Labels: 기능, 프론트엔드, 백엔드

#119 [Feature/#99] 방장 오디오 조절 버그 수정
  client/src/components/room/ControlBar.tsx
  client/src/components/room/monitor/index.tsx
  client/src/hooks/socket/useIsStreamOnOff.ts
  client/src/hooks/socket/useUser.ts
  client/src/socket/isStreamOnOff.ts
  client/src/socket/isVideoOnOff.ts
  client/src/socket/socket.ts
  client/src/socket/user.ts
  server/src/controller/socket/entering.ts
  server/src/controller/socket/restricting.ts
  server/src/controller/socket/streamChange.ts
  server/src/loader/socket.ts
Labels: 오류, 리팩토링

#138 [Feature/#96] 마이페이지 친구 기능 구현
  client/src/api/friend.ts
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/components/icons/HomeIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/user-information/FriendItem.style.js
  client/src/components/user-information/FriendItem.tsx
  client/src/components/user-information/FriendList.style.js
  client/src/components/user-information/FriendList.tsx
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/MainData.tsx
  client/src/components/user-information/modals/DeleteFriendModal.tsx
  client/src/components/user-information/modals/FriendRequestModal.tsx
  client/src/components/user-information/modals/NicknameChangeModal.tsx
  client/src/components/user-information/modals/NicknameLogModal.tsx
  client/src/index.tsx
  client/src/store/store.ts
  server/src/api/v1/friend.ts
  server/src/controller/socket/logController.ts
  server/src/models/User.ts
Labels: 기능, 스타일, 프론트엔드, 백엔드

#139 [Feature/#87] 프로필 변경 모달 수정 및 프로필 사진 변경 기능 구현중
  client/public/images/profileBox.svg
  client/src/api/user.ts
  client/src/components/icons/AcceptIcon.tsx
  client/src/components/icons/CancelIcon.tsx
  client/src/components/icons/DeleteIcon.tsx
  client/src/components/icons/GreenXButtonIcon.tsx
  client/src/components/icons/ProfileSquareIcon.tsx
  client/src/components/icons/RejectIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/room/host/RoomController.tsx
  client/src/components/user-information/Information.style.ts
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/modals/DeleteFriendModal.tsx
  client/src/components/user-information/modals/NicknameChangeModal.tsx
  client/src/components/user-information/modals/NicknameLogModal.tsx
  client/src/constant/style.js
  client/src/pages/UserInformation.tsx
  server/src/controller/user/user.ts
Labels: 기능, 리팩토링, 스타일, 프론트엔드, 백엔드

#143 [Feature/#100] 친구 조회 및 삭제 기능 구현
  client/src/api/friend.ts
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/components/user-information/FriendList.tsx
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/modals/DeleteFriendModal.tsx
  client/src/components/user-information/modals/FriendInfoModal.tsx
  client/src/components/user-information/modals/FriendRequestModal.tsx
  client/src/components/user-information/modals/NicknameLogModal.tsx
  server/src/api/v1/friend.ts
  server/src/controller/user/user.ts
  server/src/models/User.ts
Labels: 기능, 프론트엔드, 백엔드

#148 [Feature/#145] 서버 라우터, 컨트롤러 분리 등 리팩토링
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/components/custom/Dropdown.style.js
  client/src/components/room/RoomMenu.tsx
  client/src/components/room/RouteMenu.tsx
  client/src/components/room/index.tsx
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/Ranking.style.js
  client/src/components/user-information/Ranking.tsx
  client/src/components/user-information/RankingBox.style.js
  client/src/components/user-information/RankingBox.tsx
  client/src/components/user-information/modals/FriendInfoModal.tsx
  client/src/components/user-information/modals/FriendRequestModal.tsx
  client/src/components/user/Users.tsx
  client/src/hooks/socket/useEnterSocket.ts
  client/src/pages/UserInformation.tsx
  client/src/socket/enter.ts
  server/src/api/v1/auth.ts
  server/src/api/v1/friend.ts
  server/src/api/v1/rank.ts
  server/src/api/v1/user.ts
  server/src/controller/friend.ts
  server/src/controller/rank.ts
  server/src/controller/user.ts
  server/src/controller/user/rank.ts
  server/src/controller/user/user.ts
  server/src/models/User.ts
  server/src/utils/error.ts
  server/src/utils/transaction.ts
  server/src/utils/userCount.ts
Labels: 리팩토링, 백엔드

#147 [Feature/#87] 프로필 이미지 변경하기
  client/public/images/humanIcon.svg
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/components/icons/CloseIcon.tsx
  client/src/components/icons/NicknameChangeIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/user-information/Information.style.ts
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/modals/NicknameChangeModal.tsx
  client/src/store/user.ts
  client/src/utils/request.ts
  server/public/uploads/humanIcon.svg
  server/src/api/v1/user.ts
  server/src/app.ts
  server/src/controller/user.ts
  server/src/utils/error.ts
Labels: 기능, 리팩토링, 도와줘요, 스타일, 프론트엔드, 백엔드

#152 [Feature/#149] 게임 설명창, 랭킹 페이지 레이아웃 수정
  client/src/components/icons/GameRuleIcon.tsx
  client/src/components/icons/LiarGameIcon.tsx
  client/src/components/icons/UpdownGameIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/room/games/GameBox.tsx
  client/src/components/room/games/GameMenu.style.js
  client/src/components/room/games/GameMenu.tsx
  client/src/components/room/games/gameList.tsx
  client/src/components/user-information/Ranking.style.js
  client/src/components/user-information/Ranking.tsx
  client/src/components/user-information/RankingBox.style.js
  client/src/hooks/socket/useGameSocket.ts
  client/src/pages/UserInformation.style.js
  domain/constant/gameName.ts
  server/src/controller/socket/game.ts
  server/src/controller/socket/vote.ts
Labels: 스타일, 프론트엔드

#151 [Feature/#91] 각종 로그 저장
  client/src/App.tsx
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/components/user-information/Information.tsx
  server/src/api/v1/auth.ts
  server/src/api/v1/user.ts
  server/src/constant.ts
  server/src/controller/friend.ts
  server/src/controller/socket/animation.ts
  server/src/controller/socket/chat.ts
  server/src/controller/socket/game.ts
  server/src/controller/socket/mark.ts
  server/src/controller/socket/vote.ts
  server/src/controller/user.ts
  server/src/utils/log.ts
Labels: 기능, 백엔드

#154 [hotfix] 게임 관련 CSS 수정
  client/src/components/room/games/GameBox.style.js
  client/src/components/room/games/GameMenu.style.js
Labels: 기능, 리팩토링, 도와줘요, 스타일, 프론트엔드, 백엔드

#155 [Feature/#150] 각종 프로필 정보 리팩토링
  client/src/components/user-information/FriendItem.style.js
  client/src/components/user-information/FriendList.style.js
  client/src/components/user-information/InfoComponent.tsx
  client/src/components/user-information/Information.style.ts
  client/src/components/user-information/Information.tsx
  client/src/components/user-information/modals/FriendInfoModal.tsx
  client/src/components/user-information/modals/NicknameChangeModal.tsx
  client/src/constant/style.js
Labels: 기능, 리팩토링, 스타일, 프론트엔드, 백엔드

#160 [Feature/#157] 에러 컴포넌트 CSS 적용
  client/src/api/user.ts
  client/src/components/custom/ErrorToast.style.ts
  client/src/components/custom/ErrorToast.tsx
  domain/constant/addition.ts
Labels: 기능, 스타일, 프론트엔드

#161 [Feature/#158] 화상채팅방 css 수정
  client/src/components/room/monitor/index.style.ts
  client/src/components/room/monitor/index.tsx
  client/src/components/user/Users.style.js
Labels: 기능, 스타일, 프론트엔드

#163 [Feature/#123] 드롭박스 CSS & 화상채팅방 반절 반응형
  client/src/components/custom/Dropdown.style.js
  client/src/components/custom/Dropdown.tsx
  client/src/components/room/animation-screen/index.tsx
  client/src/components/room/monitor/index.style.ts
  client/src/components/room/monitor/index.tsx
  client/src/components/setting/SettingDropdown.style.js
  client/src/components/setting/SettingDropdown.tsx
  client/src/components/setting/index.style.js
  client/src/components/setting/index.tsx
  client/src/sagas/device.ts
  client/src/store/device.ts
  client/src/utils/customRTC.ts
  client/src/utils/regExpr.ts
Labels: 기능, 리팩토링, 스타일

#168 [feature/#130] 업다운게임 렌더링될때 랜덤숫자 변경되는 버그 수정
  client/src/components/room/games/UpdownGame.tsx
  client/src/components/room/games/index.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/socket/game.ts
  server/src/controller/socket/game.ts
Labels: 프론트엔드, 백엔드

#175 [Feature/#173] 오브젝트 스토리지 추가 & db index적용 & 리팩토링
  client/src/components/user-information/modals/NickChangeModal.tsx
  domain/constant/addition.ts
  server/package.json
  server/src/api/v1/user.ts
  server/src/app.ts
  server/src/constant.ts
  server/src/controller/rank.ts
  server/src/controller/user.ts
  server/src/models/NicknameLog.ts
  server/src/models/User.ts
  server/src/utils/cron.ts
  server/src/utils/updateRank.ts
  server/uploads/HumanIcon.svg
Labels: 리팩토링, 백엔드

#174 [Feature/#146] 유저 페이지 스타일링 개선
  client/src/components/icons/AcceptIcon.tsx
  client/src/components/icons/CloseIcon.tsx
  client/src/components/icons/index.ts
  client/src/components/user-information/UserHeader.style.ts
  client/src/components/user-information/friend-list/FriendItem.style.js
  client/src/components/user-information/friend-list/FriendItem.tsx
  client/src/components/user-information/friend-list/index.style.js
  client/src/components/user-information/friend-list/index.tsx
  client/src/components/user-information/information/UserData.style.js
  client/src/components/user-information/information/UserData.tsx
  client/src/components/user-information/information/UserProfile.style.js
  client/src/components/user-information/information/UserProfile.tsx
  client/src/components/user-information/modals/FriendInfoModal.style.js
  client/src/components/user-information/modals/FriendRequestModal.style.js
  client/src/components/user-information/modals/FriendRequestModal.tsx
  client/src/components/user-information/modals/NickChangeModal.style.js
  client/src/components/user-information/modals/NickChangeModal.style.ts
  client/src/components/user-information/modals/NickChangeModal.tsx
  client/src/components/user-information/modals/NickLogModal.style.js
  client/src/components/user-information/modals/NickLogModal.tsx
  client/src/components/user-information/modals/index.style.js
  client/src/pages/UserPage.style.js
  client/src/utils/date.ts
Labels: 리팩토링, 스타일

#179 [Hotfix] Merge 이후 짜잘한 오류 해결
  client/src/components/user-information/information/UserData.tsx
  server/src/app.ts
  server/src/service/rank.ts
  server/src/utils/cron.ts
  server/src/utils/updateRank.ts
Labels: 오류
