Repository boostcampwm-2021/web12-sooltreaming, pull requests merged in 2021-12, with the labels that each got.

#187 [Feature/#182] 프론트 웹으로서 최적화 하기
  client/package.json
  client/public/android-chrome-192x192.png
  client/public/android-chrome-512x512.png
  client/public/apple-touch-icon.png
  client/public/browserconfig.xml
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/images/logo.png
  client/public/index.html
  client/public/mstile-150x150.png
  client/public/robots.txt
  client/public/safari-pinned-tab.svg
  client/public/site.webmanifest
  client/src/App.tsx
  client/src/pages/JoinRoom.tsx
  client/src/pages/Login.tsx
Labels: 기능, 리팩토링, 프론트엔드, 설정

#186 [Feature/#183] questionMark debounce 추가
  client/src/socket/mark.ts
Labels: 리팩토링, 프론트엔드

#188 [feature/#184] webRTC 연결 잘 안되던 버그 해결
  client/src/hooks/socket/useSignalSocket.ts
  client/src/hooks/useUpdateStream.ts
  client/src/socket/signal.ts
Labels: 프론트엔드

#194 [Feature/#169] 세션 만료 Error 처리
  client/src/api/friend.ts
  client/src/api/index.ts
  client/src/api/rank.ts
  client/src/api/user.ts
  client/src/components/custom/ErrorToast.tsx
  client/src/components/user-information/information/index.tsx
  client/src/components/user-information/modals/FriendDeleteModal.tsx
  client/src/components/user-information/modals/FriendRequestModal.tsx
  client/src/components/user-information/modals/NickChangeModal.tsx
  client/src/components/user-information/ranks/index.tsx
  client/src/hooks/socket/useFriendSocket.ts
  client/src/sagas/friend.ts
  client/src/store/friend.ts
  client/src/store/notice.ts
  client/src/store/user.ts
  server/src/constant.ts
  server/src/controller/friend.ts
  server/src/controller/socket/control.ts
  server/src/controller/socket/enter.ts
  server/src/controller/user.ts
  server/src/utils/error.ts
Labels: 리팩토링, 프론트엔드, 백엔드

#195 [Feature/#170] 프로필 이미지 변경 시 원래 저장되어있던 이미지 삭제
  server/src/api/v1/user.ts
  server/src/constant.ts
  server/src/service/user.ts
Labels: 기능, 백엔드

#198 [Hotfix] logout시 페이지 이동되지 않는 버그 수정
  client/src/api/user.ts
  client/src/components/Header.tsx
Labels: 오류

#200 [Feature/#146] 랭킹 CSS 수정 및 logo 이미지 크기 변경
  client/src/components/Header.style.js
  client/src/components/user-information/ranks/RankingBox.style.js
  client/src/components/user-information/ranks/index.style.js
Labels: 리팩토링, 스타일, 프론트엔드

#202 [Feature/#197] 로그아웃 수정 및 기타 다양한 오류 수정
  client/src/components/room/RouteMenu.tsx
  client/src/components/room/host/Participant.style.js
  client/src/components/user-information/modals/NickChangeModal.tsx
  client/src/components/user/Users.style.js
  client/src/components/user/Users.tsx
Labels: 기능, 리팩토링, 스타일, 프론트엔드

#201 [Feature/#199] warning 해결
  client/src/App.tsx
  client/src/components/Header.style.js
  client/src/components/Header.tsx
  client/src/components/custom/ErrorToast.style.ts
  client/src/components/room/animation-screen/index.tsx
  client/src/components/room/games/RandomPickGame.style.js
  client/src/socket/stream.ts
  client/src/utils/customRTC.ts
Labels: 리팩토링

#203 [Feature/#185] Video/Audio 트랙을 종료/재시작 으로 On/Off 구현
  client/src/components/room/monitor/OtherVideo.tsx
  client/src/components/setting/DeviceSelections.tsx
  client/src/components/setting/DeviceToggles.tsx
  client/src/hooks/socket/useSignalSocket.ts
  client/src/sagas/device.ts
  client/src/socket/signal.ts
  client/src/store/device.ts
  client/src/utils/customRTC.ts
Labels: 기능, 리팩토링, 프론트엔드

#204 [Hotfix] 마지막으로 여러가지 버그 수정
  client/src/components/room/host/ParticipantController.tsx
  client/src/components/room/monitor/OtherVideo.tsx
  client/src/components/room/scaffold/TimerBomb.tsx
  client/src/components/user/Users.tsx
  client/src/sagas/device.ts
  client/src/socket/signal.ts
  client/src/store/device.ts
  client/src/ts-types/store.ts
Labels: 오류

#106 [Documentation] Ground Rule 링크 수정
  README.md
Labels: 문서

#206 [Hotfix] 메타데이터 수정 및 필요없는 코드 제거
  client/public/index.html
  client/src/components/icons/LogoutIcon.tsx
  client/src/components/user-information/modals/FriendDeleteModal.style.js
  client/src/components/user-information/modals/FriendDeleteModal.tsx
  client/src/components/user-information/modals/FriendRequestModal.style.js
  client/src/components/user-information/modals/NickLogModal.style.js
  client/src/components/user-information/modals/index.style.js
  client/src/components/user-information/ranks/RankingBox.style.js
  client/src/components/user-information/ranks/RankingBox.tsx
  client/src/components/user-information/ranks/index.style.js
  client/src/components/user-information/ranks/index.tsx
  server/src/models/LiarGameKeywords.ts
Labels: 문서, 리팩토링
